// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1ErGjdLG6VL7abwKVKel-DXZQPY_0UG4',
    appId: '1:843066245033:web:ae432a2a1c1a2b38948eb8',
    messagingSenderId: '843066245033',
    projectId: 'shop-now-cc5ef',
    authDomain: 'shop-now-cc5ef.firebaseapp.com',
    storageBucket: 'shop-now-cc5ef.firebasestorage.app',
    measurementId: 'G-F90LYX0RH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa81xbN69xgu-XfeneYoye-aVys4TdgQk',
    appId: '1:843066245033:android:924efa5cd8b227c4948eb8',
    messagingSenderId: '843066245033',
    projectId: 'shop-now-cc5ef',
    storageBucket: 'shop-now-cc5ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUQaCWIR69AvTUMIBQnGxlf-MOnalPTXs',
    appId: '1:843066245033:ios:82d7d810fd4fe5bd948eb8',
    messagingSenderId: '843066245033',
    projectId: 'shop-now-cc5ef',
    storageBucket: 'shop-now-cc5ef.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUQaCWIR69AvTUMIBQnGxlf-MOnalPTXs',
    appId: '1:843066245033:ios:82d7d810fd4fe5bd948eb8',
    messagingSenderId: '843066245033',
    projectId: 'shop-now-cc5ef',
    storageBucket: 'shop-now-cc5ef.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1ErGjdLG6VL7abwKVKel-DXZQPY_0UG4',
    appId: '1:843066245033:web:caa4b1421e5f9691948eb8',
    messagingSenderId: '843066245033',
    projectId: 'shop-now-cc5ef',
    authDomain: 'shop-now-cc5ef.firebaseapp.com',
    storageBucket: 'shop-now-cc5ef.firebasestorage.app',
    measurementId: 'G-YE595P6N87',
  );

}